# Generated by Django 4.2.5 on 2023-11-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizresult_quiz_creator_quiz_question_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_amount',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quizzes.question'),
        ),
    ]
