# Generated by Django 4.2.5 on 2023-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizresult_quiz_creator_quiz_question_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='quizzes.question'),
        ),
    ]
