# Generated by Django 4.2.5 on 2023-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=15),
        ),
        migrations.AlterField(
            model_name='companyrequests',
            name='request_type',
            field=models.CharField(choices=[('company to user', 'Company To User'), ('user to company', 'User To Company')]),
        ),
    ]
