# Generated by Django 4.2.5 on 2023-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembers',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('common', 'COMMON')], default='common'),
        ),
    ]
