name: CI Python pull request/commit checking

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./meduzzen_backend/requirements.txt

      - name: Lint
        run: ruff check .

      - name: Test
        env:
          DJANGO_SETTINGS_MODULE: meduzzen_backend.settings
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          FRONTEND_URL: http://localhost:5173
        working-directory: ./meduzzen_backend
        run: pytest
