name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11.3-alpine

    services:
      postgres-db:
        image: postgres:latest
        env:
          POSTGRES_DB: meduzzen_backend
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest
        env:
          DJANGO_SETTINGS_MODULE: meduzzen_backend.settings
