name: Quality Assurance
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:latest
        env:
          POSTGRES_DB: meduzzen_backend
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest
        env:
          DJANGO_SETTINGS_MODULE: meduzzen_backend.settings
